{{- if or .Values.foundry.config.s3 .Values.foundry.config.certificates.cert .Values.foundry.config.certificates.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundryvtt.fullname" . }}-config
  labels:
    {{- include "foundryvtt.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.foundry.config.s3 }}
  {{- if kindIs "string" .Values.foundry.config.s3 }}
  s3-config.json: {{ .Values.foundry.config.s3 | b64enc | quote }}
  {{- else }}
  s3-config.json: {{ .Values.foundry.config.s3 | toJson | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.foundry.config.certificates.cert }}
  cert: {{ .Values.foundry.config.certificates.cert | b64enc | quote }}
  {{- end }}
  {{- if .Values.foundry.config.certificates.key }}
  key: {{ .Values.foundry.config.certificates.key | b64enc | quote }}
  {{- end }}
{{- end }}
