apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundryvtt.fullname" . }}
  labels:
    {{- include "foundryvtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.foundry.releaseUrl }}
  foundry-release-url: {{ .Values.foundry.releaseUrl | quote }}
  {{- end }}
  {{- if .Values.foundry.auth.username }}
  foundry-username: {{ .Values.foundry.auth.username | quote }}
  {{- end }}
  {{- if .Values.foundry.auth.password }}
  foundry-password: {{ .Values.foundry.auth.password | quote }}
  {{- end }}
  {{- if .Values.foundry.admin.key }}
  foundry-admin-key: {{ .Values.foundry.admin.key | quote }}
  {{- end }}
  {{- if .Values.foundry.licenseKey }}
  foundry-license-key: {{ .Values.foundry.licenseKey | quote }}
  {{- end }}
